from models import User, FantasyLeague, FantasyTeam, Player, Game
from config import app, db
from random import choice

with app.app_context():
    User.query.delete()
    FantasyLeague.query.delete()
    FantasyTeam.query.delete()
    Player.query.delete()
    Game.query.delete()

    user1 = User(
        name="Demitry",
        username="demixyz773",
        _password_hash="12323nsdghdsflng12ou4y23o4",
    )
    user2 = User(
        name="Billy Lowry",
        username="billylowry",
        _password_hash="12432ouhfskdjf7i9w4rw4r4",
    )
    user3 = User(
        name="Yemi A",
        username="tim",
        _password_hash="12432546744375349w4rw4r4",
    )
    user4 = User(
        name="Victoria P.",
        username="vicky123",
        _password_hash="7645762nsdghdsflng12ou4y23o4",
    )
    user5 = User(
        name="Ashley F.",
        username="AshTheBest",
        _password_hash="124564754576576i9w4rw4r4",
    )
    user6 = User(
        name="Mandy Moore",
        username="IGotCandy",
        _password_hash="124325467443754747556474",
    )
    user7 = User(
        name="Kelly Clarkson",
        username="BreakAway",
        _password_hash="12323nsd453454365435o4",
    )
    user8 = User(
        name="Andrew E.",
        username="transformers1",
        _password_hash="12432ouh474ndyf74h3e4r4",
    )
    user9 = User(
        name="Celina D.",
        username="Olive123",
        _password_hash="124322222009585nf121324r4",
    )
    user10 = User(
        name="David G",
        username="GolfMan123",
        _password_hash="1243@#$#%$#%DFgfd4e23234",
    )

    users = [user1, user2, user3, user4, user5, user6, user7, user8, user9, user10]
    db.session.add_all(users)

    league1 = FantasyLeague(name="Flatiron Gang")

    db.session.add(league1)

    team1 = FantasyTeam(
        team_name="Strawberry Truthers",
        user=choice(users),
        league_id=1,
    )
    team2 = FantasyTeam(
        team_name="In Mahomes I Trust",
        user=choice(users),
        league_id=1,
    )
    team3 = FantasyTeam(
        team_name="Kittle Taste The Rainbow",
        user=choice(users),
        league_id=1,
    )
    team4 = FantasyTeam(
        team_name="Crazy 4 Kelce",
        user=choice(users),
        league_id=1,
    )
    team5 = FantasyTeam(
        team_name="Tux Down",
        user=choice(users),
        league_id=1,
    )
    team6 = FantasyTeam(
        team_name="Fly Eagles Fly",
        user=choice(users),
        league_id=1,
    )
    team7 = FantasyTeam(
        team_name="Amy's Amazing Team",
        user=choice(users),
        league_id=1,
    )
    team8 = FantasyTeam(
        team_name="Crazy 4 Brady",
        user=choice(users),
        league_id=1,
    )
    team9 = FantasyTeam(
        team_name="Stairway to 7",
        user=choice(users),
        league_id=1,
    )
    team10 = FantasyTeam(
        team_name="Manning maddening",
        user=choice(users),
        league_id=1,
    )

    teams = [team1, team2, team3, team4, team5, team6, team7, team8, team9, team10]
    db.session.add_all(teams)

    player22 = Player(
        name="Patrick Mahomes",
        position="QB",
        nfl_team="Kansas City Chiefs",
        bye_week=10,
        fantasy_team_id=1,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player23 = Player(
        name="Joe Burrow",
        position="QB",
        nfl_team="Cincinnati Bengals",
        bye_week=7,
        fantasy_team_id=2,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player24 = Player(
        name="Justin Jefferson",
        position="WR",
        nfl_team="Minnesota Vikings",
        bye_week=13,
        fantasy_team_id=3,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player1 = Player(
        name="Kylar Murray",
        position="QB",
        nfl_team="Arizona Cardinals",
        bye_week=14,
        fantasy_team_id=choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player2 = Player(
        name="Colt McCoy",
        position="QB",
        nfl_team="Arizona Cardinals",
        bye_week=14,
        fantasy_team_id=choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player3 = Player(
        name="James Conner",
        position="RB",
        nfl_team="Arizona Cardinals",
        bye_week=14,
        fantasy_team_id=choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player4 = Player(
        name="Keaontay Ingram",
        position="RB",
        nfl_team="Arizona Cardinals",
        bye_week=14,
        fantasy_team_id=choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player5 = Player(
        name="Marquise Brown",
        position="WR",
        nfl_team="Arizona Cardinals",
        bye_week=14,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player6 = Player(
        name="Rondale Moore",
        position="WR",
        nfl_team="Arizona Cardinals",
        bye_week=14,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player7 = Player(
        name="Greg Dortch",
        position="TE",
        nfl_team="Arizona Cardinals",
        bye_week=14,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player8 = Player(
        name="Trey McBride",
        position="TE",
        nfl_team="Arizona Cardinals",
        bye_week=14,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player9 = Player(
        name="Zach Ertz",
        position="TE",
        nfl_team="Arizona Cardinals",
        bye_week=14,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player10 = Player(
        name="Cardinals D/ST",
        position="D/ST",
        nfl_team="Arizona Cardinals",
        bye_week=14,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player11 = Player(
        name="Desmond Ridder",
        position="QB",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player12 = Player(
        name="Taylor Heinicke",
        position="QB",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player13 = Player(
        name="Bijan Robinson",
        position="RB",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player14 = Player(
        name="Tyler Allgeier",
        position="RB",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player15 = Player(
        name="Cordarrelle Patterson",
        position="WR",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player16 = Player(
        name="Drake London",
        position="WR",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player17 = Player(
        name="Mack Hollins",
        position="WR",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player18 = Player(
        name="Scott Miller",
        position="WR",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player19 = Player(
        name="Kyle Pitts",
        position="TE",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player20 = Player(
        name="Jonnu Smith",
        position="TE",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )
    player21 = Player(
        name="Falcons D/ST",
        position="D/ST",
        nfl_team="Atlanta Falcons",
        bye_week=11,
        week_1_points=0,
        week_2_points=0,
        week_3_points=0,
        week_4_points=0,
        week_5_points=0,
        week_6_points=0,
        week_7_points=0,
        week_8_points=0,
        week_9_points=0,
        week_10_points=0,
        week_11_points=0,
        week_12_points=0,
        week_13_points=0,
        week_14_points=0,
        playoff_points=0,
        championship_points=0,
    )

    players = [
        player1,
        player2,
        player3,
        player4,
        player5,
        player6,
        player7,
        player8,
        player9,
        player10,
        player11,
        player12,
        player13,
        player14,
        player15,
        player16,
        player17,
        player18,
        player19,
        player20,
        player21,
    ]
    db.session.add_all(players)

    game1 = Game(team_1_id=1, team_2_id=2, team_1_score=0, team_2_score=0, winner_id=1)
    game2 = Game(team_1_id=2, team_2_id=3, team_1_score=0, team_2_score=0, winner_id=2)
    game3 = Game(team_1_id=1, team_2_id=3, team_1_score=0, team_2_score=0, winner_id=3)

    games = [game1, game2, game3]
    db.session.add_all(games)
    db.session.commit()
