"""empty message

Revision ID: 18defe523842
Revises: 
Create Date: 2023-06-26 20:14:42.648737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18defe523842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fantasy_leagues'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('fantasy_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['fantasy_leagues.id'], name=op.f('fk_fantasy_teams_league_id_fantasy_leagues')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fantasy_teams_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fantasy_teams'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('team_1_id', sa.Integer(), nullable=True),
    sa.Column('team_2_id', sa.Integer(), nullable=True),
    sa.Column('team_1_score', sa.Integer(), nullable=True),
    sa.Column('team_2_score', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_1_id'], ['fantasy_teams.id'], name=op.f('fk_games_team_1_id_fantasy_teams')),
    sa.ForeignKeyConstraint(['team_2_id'], ['fantasy_teams.id'], name=op.f('fk_games_team_2_id_fantasy_teams')),
    sa.ForeignKeyConstraint(['winner_id'], ['fantasy_teams.id'], name=op.f('fk_games_winner_id_fantasy_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('nfl_team', sa.String(), nullable=False),
    sa.Column('bye_week', sa.Integer(), nullable=False),
    sa.Column('week_1_points', sa.Integer(), nullable=True),
    sa.Column('week_2_points', sa.Integer(), nullable=True),
    sa.Column('week_3_points', sa.Integer(), nullable=True),
    sa.Column('week_4_points', sa.Integer(), nullable=True),
    sa.Column('week_5_points', sa.Integer(), nullable=True),
    sa.Column('week_6_points', sa.Integer(), nullable=True),
    sa.Column('week_7_points', sa.Integer(), nullable=True),
    sa.Column('week_8_points', sa.Integer(), nullable=True),
    sa.Column('week_9_points', sa.Integer(), nullable=True),
    sa.Column('week_10_points', sa.Integer(), nullable=True),
    sa.Column('week_11_points', sa.Integer(), nullable=True),
    sa.Column('week_12_points', sa.Integer(), nullable=True),
    sa.Column('week_13_points', sa.Integer(), nullable=True),
    sa.Column('week_14_points', sa.Integer(), nullable=True),
    sa.Column('playoff_points', sa.Integer(), nullable=True),
    sa.Column('championship_points', sa.Integer(), nullable=True),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], name=op.f('fk_players_fantasy_team_id_fantasy_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('fantasy_teams')
    op.drop_table('users')
    op.drop_table('fantasy_leagues')
    # ### end Alembic commands ###
