"""empty message

Revision ID: 725a63248aba
Revises: 18defe523842
Create Date: 2023-06-26 20:20:02.547321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725a63248aba'
down_revision = '18defe523842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('fk_games_winner_id_fantasy_teams', type_='foreignkey')
        batch_op.drop_constraint('fk_games_team_2_id_fantasy_teams', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_games_team_2_id_fantasy_teams', 'fantasy_teams', ['team_2_id'], ['id'])
        batch_op.create_foreign_key('fk_games_winner_id_fantasy_teams', 'fantasy_teams', ['winner_id'], ['id'])

    # ### end Alembic commands ###
